repository: SeanFromIT/studentloanbilltracker
theme: jekyll-theme-minimal
title: Student Loan Bill Tracker
description: Track the status of United States legislation to solve the student loan debt crisis.
google_analytics: G-990EQCNSK6
plugins:
  - jekyll-sitemap
